services:
  postgres-payments:
    image: postgres:15-alpine
    container_name: bakery-payments-db
    restart: unless-stopped
    ports:
      - "5435:5432"  # Different port for payment service
    environment:
      POSTGRES_DB: bakery_payments
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_payments_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - bakery-network

volumes:
  postgres_payments_data:
    driver: local

networks:
  bakery-network:
    driver: bridge
